### ISSUE TITLE
When using "chapref" option, "References" sections were automatically added into unwanted sections (i.e., after "Abstract", "Acknowledgements" etc.)

### ISSUE THREAD

**Issue by PaleoLipidRR** [kwodzicki/TAMU_Thesis_KRW#1]
Hi kwodzicki,

I have forked your "TAMU_Thesis_KRW" Overleaf Latex Template as I am preparing my PhD dissertation. I like your template over the official template provided by OGAPS because your template allow us to add the footnote for the chapter title easily. As I am preparing the dissertation following the "Journal Article Style," I have tried to call "chapref" option in the preamble section. The function works fine in chapters with in-text citations. HOWEVER, the function also added "REFERENCES" sections into other unwanted sections, such as after Abstract, Acknowledgements, etc [sections that do not need to have references].

I am not sure if there is an easy way that we can suppress the "REFERENCES" for sections that we don't want to have the references or not.

Here is the link of the Overleaf Latex project that I am currently working on: https://www.overleaf.com/3382617364yrhmydxwmncc

Please let me know if you need any further information from me to help me solve the issue.
I look forward to hearing from you soon.

Below is an example of the extra pages of "References" in the unwanted sections.
![image](https://github.com/kwodzicki/TAMU_Thesis_KRW/assets/55888172/6c1fdd48-1dad-4394-b490-a3e070a31c96)

Best,
Ronnie

**Comment by kwodzicki** [comment]
Hey @PaleoLipidRR ,

I poked around in your document a little bit and it seems like you got a work around for the problem. I'm not really sure what the issue is as when I imported the repo into Overleaf and compiled it it seems like the `chapref` option works as intended; i.e., no extra section in Dedication, etc.

I grabbed a copy of you document and will mess with it offline; don't want to break anything major for you. Will let you know if I can implement a fix for it.

Hope everything else is the template is working and good luck finishing everything up!

**Comment by kwodzicki** [comment]
@PaleoLipidRR did some more digging and it seems that the issue is that `natbib` and the `apalike` citation style are incompatible, at least in the context of this template.

To test this, I removed your imports of `bibentry`, `natabib`, and `chapterbib` around line 110 of the main TeX document (left all other imports for rotating pages, etc.).
I also un-commented the `\makebibliography` command near the end of the file.
For the `\documentclass` command I added the `chapref` and `natbib` options.
For the bibliography style, I tried the one that I used for my thesis (the American Meteorological Society; attached, will have to change extension back to `.bst`).

I then removed the manual addition of the reference section in the various `Data/*.tex` files.

This ran with no errors and no extra reference sections. I have shared the 'testing' document with you on Overleaf.

If you _need_ to use the `apalike` style and `natbib` commands (e.g., `\citep`, `\citet`) I think your best option is the changes you made. Otherwise I'd recommend using a style that fully supports `natbib` (such as the ametsoc one) or using cite command support by the `apalike` style. 

Let me know if you have any other issues or ideas. I will leave this issue open for now.

[ametsocV6.txt](https://github.com/kwodzicki/TAMU_Thesis_KRW/files/11752193/ametsocV6.txt)

**Comment by PaleoLipidRR** [comment]
Thank you @kwodzicki for your time and effort in digging into my document! I would consider myself a beginner user when it comes to LaTeX! I will try out your suggestions and will let you know if I find any issues. If not, we can close the case. Thank you very much!!

Best,
Ronnie

**Comment by PaleoLipidRR** [comment]
Hi @kwodzicki, I think I like your suggested changes. So, I will close this issue!
